
language:
        - cpp
        - c

compiler:
        - gcc


addons:
   apt:
      packages:
         # Travis doesn't include fortran compiler as 
         # default we download it 
         - gfortran

script:
        - mkdir -p build
        - cd build
        - cmake ..
        - make
        - ctest
